### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by bk1405bgl** [bk1405bgl/capstone-project#1]
## Value Proposition

**As a** User
**I want to** see a homepage
**so that** i can see the actual rentals or a message, that my collection is complete. 
​

## Description

![image](https://user-images.githubusercontent.com/67201506/222715345-c7352955-f315-441b-a775-0757a0ded549.png)
​

## Acceptance Criteria

- [ ] create a Homepage, where i can see the actual rentals
- [ ] otherwise, there should be a message displayed "Collection is complete"
      ​

## Tasks

- [ ] may be, that it should be realized with a try catch function or a if else function.
      ​

## Complexity

XS

**Comment by Manu7864z** [comment]
Hey Bilal, maybe add some more points to tasks and acceptance criteria? 
for instance: create a list or header or navbar. Give some more details 😃
