### ISSUE TITLE
Create MongoDB Database and Connect to it. Save Friends in DB

### ISSUE THREAD

**Issue by bk1405bgl** [bk1405bgl/capstone-project#12]
## Value Proposition

**As a** User
**I want to** save the created friends in a mongodb
**so that** i dont have to use localstorage or similar techniques.
​

## Acceptance Criteria

- [ ] Create a MongoDB Database
- [ ] Create a Collection "Friends"
- [ ] Create a Collection "OwnComics"
- [ ] Create a Collection "Rentals"
      ​

## Tasks

- [ ] create an .env.local file
- [ ] create a MongoDB Database and make the connection work on local and on vercel
- [ ] create friends and save them into the database and read them from the database.
      ​

## Complexity

L
