### ISSUE TITLE
Outsource Collection and Rentals data in DB and display them

### ISSUE THREAD

**Issue by kebab-case-dev** [bk1405bgl/capstone-project#13]
## Value Proposition

**As a** User
**I want** my OwnCollection and the Rentals saved in the MongoDB Database
**so that** i don't need to use localstorage or stuff like this.
​

## Acceptance Criteria

- [ ] Save the OwnCollection Components data in the DB
- [ ] Read the OwnCollection data from the database
- [ ] Save the Rentals Components data in the DB
- [ ] Read the Rentals data from the database and print to the Homepage
      ​

## Tasks

- [ ] save data of owncollection in the DB
- [ ] print saved data from DB into the ownCollection
- [ ] save the rentals in the DB
- [ ] print the saved data from DB to the Homepage so we can see actual rentals on the homepage when we start the app
      ​

## Complexity

L
