### ISSUE TITLE
Populate the db entries and show actual rents on homepage

### ISSUE THREAD

**Issue by bk1405bgl** [bk1405bgl/capstone-project#15]
## Value Proposition

**As a** User
**I want to** see the actual rents on the homepage
**so that** i know, which friend has which comic
​

## Description

![image](https://user-images.githubusercontent.com/67201506/226293460-529c7d03-cde8-47cf-92b6-19cb361f1b19.png)![image](https://user-images.githubusercontent.com/67201506/226292855-fae3ffcf-ab9d-48c0-b81d-a29fc6f04587.png)
​

## Acceptance Criteria

- [ ] when comic collection is complete (ne rentals), message should be shown that the collection is complete
- [ ] when at least one comic is rent to a friend, it should be displayed on homepage
      ​

## Tasks

- [ ] at this point, the days counter will not be displayed.
- [ ] use the populate() function of mongodb, to show actual rents without any need of Rentals Collection on MongoDB

      ​

## Complexity

L
