### ISSUE TITLE
Display Details Page of own Collection with Rent Button

### ISSUE THREAD

**Issue by bk1405bgl** [bk1405bgl/capstone-project#18]
## Value Proposition

**As a** User
**I want to** see the details of the comic in my own collection
**so that** i can rent it from there to one of my friends
​

## Description

![image](https://user-images.githubusercontent.com/67201506/227575223-4a86527b-bbd3-41da-b413-f54e2bb68090.png)
​

## Acceptance Criteria

- [ ] show a detail page of the comic in own collection
- [ ] dropdown menu with friendsnames
- [ ] button to rent this comic to this selected friend
- [ ] may be show status of comic, if it is rent or available
      ​

## Tasks

- [ ] create details page of comic in own collection
- [ ] get friends in dropdown menu from db
- [ ] when rent to a friend, set the comic id into the friend data     ​

## Complexity

XL
