### ISSUE TITLE
Friends Page

### ISSUE THREAD

**Issue by bk1405bgl** [bk1405bgl/capstone-project#2]
## Value Proposition

**As a** User
**I want to** add new friends into my friends-list.  
**so that** this friends can rent my comics in future steps.
​

## Description

![image](https://user-images.githubusercontent.com/67201506/222737975-548ab19d-46c5-4727-8ead-064d503e912d.png)
​

## Acceptance Criteria

- [ ] I want to type in the name of my friend.
- [ ] I want to submit the information to save my friend in my friends-list.
- [ ] Under the form must be a list of my friends.
      ​

## Tasks

- [ ] create a form including title & label
- [ ] one textfield for the name
- [ ] one submit button
      ​

## Complexity

S

**Comment by Manu7864z** [comment]
maybe add "create a dynamic" list to tasks.
