### ISSUE TITLE
Testings

### ISSUE THREAD

**Issue by bk1405bgl** [bk1405bgl/capstone-project#21]
## Value Proposition

**As a** developer
**I want to** run tests
**so that** i can be sure, everything works well
​

## Description

test 5 components, if they are rendered (displayed) well
​

## Acceptance Criteria

- [ ] write 5 tests for components

      ​

## Tasks

- [ ] write tests for 5 different components
- [ ] test with `npm run test`

      ​

## Complexity

S
