### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by bk1405bgl** [bk1405bgl/capstone-project#22]
## Value Proposition

**As a** developer
**I want to** be sure, the app is accessible with aria-labels for every element
**so that** my app will be user-friendly
​

## Acceptance Criteria

- [ ] Add aria-labels to every html element
- [ ] test with lighthouse

      ​

## Tasks

- [ ] add aria-labels for html elements
- [ ] test with lighthouse
      ​

## Complexity

M
