### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by bk1405bgl** [bk1405bgl/capstone-project#23]
## Value Proposition

**As a** developer
**I want to** clean up my code
**so that** i can be sure, there is no unnecessary code
​

## Acceptance Criteria

- [ ] delete unnecessary code-lines

## Tasks

- [ ] refactor code
- [ ] delete unnecessary code lines
- [ ] make a few comments to the code-parts
      ​

## Complexity

M
