### ISSUE TITLE
Own Collection

### ISSUE THREAD

**Issue by bk1405bgl** [bk1405bgl/capstone-project#3]
## Value Proposition

**As a** User
**I want to** receive the comics over the API and reproduce my own physical collection  
**so that** i can create rentals related to my friends.
​

## Description

![image](https://user-images.githubusercontent.com/67201506/222749111-f8bf7c5d-b1e2-4e6e-a74d-3e63e1dfaee4.png)
​

## Acceptance Criteria

- [ ] Grid of comic thumbnails, which are actually in my physical collection
- [ ] When clicking a cover, than show details.
- [ ] Maybe later, already rent comics could be displayed gray in the overview page
      ​

## Tasks

- [ ] get information from Marvel API
- [ ] list covers in grid-system
- [ ] show detail page when selecting a cover. 
      ​

## Complexity

XL
