### ISSUE TITLE
Add Button

### ISSUE THREAD

**Issue by bk1405bgl** [bk1405bgl/capstone-project#4]
## Value Proposition

**As a** User
**I want to** add comics to my collection from the api
**so that** i can update my collection.
​

## Description

![image](https://user-images.githubusercontent.com/67201506/222755132-b30047e3-71c7-4d35-bd40-b34996c7913d.png)
​

## Acceptance Criteria

- [ ] Add PLUS Button to the collection page
- [ ] when pushed the button, all comics from this api should be listed
- [ ] when selected one comic, it should be added to my collection
      ​

## Tasks

- [ ] ...
- [ ] ...
- [ ] ...
      ​

## Complexity

M

**Comment by Manu7864z** [comment]
add some tasks to your user story :)
