### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by bk1405bgl** [bk1405bgl/capstone-project#5]
## Value Proposition

**As a** User
**I want to** see a navigation bar sticky to the bottom
**so that** i can navigate through the pages. 
​

## Description

![image](https://user-images.githubusercontent.com/67201506/222759277-a0f2269b-3b00-49a4-a87b-b410285f8642.png)
​

## Acceptance Criteria

- [ ] Add Link to App Home (with Home icon)
- [ ] Add Link to Collection (with Books icon)
- [ ] Add Link to Friends (with Friends icon)
      ​

## Tasks

- [ ] the navigation bar should be sticky to the bottom
- [ ] the main part should be scrollable, where the content is displayed
      ​

## Complexity

L
