### ISSUE TITLE
Create Details Page of Comic (API Collection)

### ISSUE THREAD

**Issue by bk1405bgl** [bk1405bgl/capstone-project#8]
## Value Proposition

**As a** User
**I want to** see a detail page of the comic, when clicking on the cover  
**so that** i can see details and i can add the comic to my onw collection
​

## Description

![image](https://user-images.githubusercontent.com/67201506/224281006-4ec93686-4fad-4349-89a4-9444f0764de5.png)
​

## Acceptance Criteria

- [ ] Show a "Add to own Collection" Button on top of the page
- [ ] Show the Cover Image
- [ ] Show more details of the comic, to be absolutely sure, that this is the correct comic, that you have in real life.
- [ ] Need a Link Back to the Api Collection
      ​

## Tasks

- [ ] Fetch the Data, which comes via the API
- [ ] Display details of the comic, especially the ean/upc/isbn to be absolutely sure, that this comic is correct.
- [ ] Be able to add the selected comic in to your own collection
- [ ] Display a message, that comic is added succussfully to your own collection.
      ​

## Complexity

S
